export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR';

export const SAVE_COUNTRY_REQUEST = 'SAVE_COUNTRY_REQUEST';
export const SAVE_COUNTRY_SUCCESS = 'SAVE_COUNTRY_SUCCESS';

export const SET_MUTATIONS = 'SET_MUTATIONS';

export const SELECT_COUNTRY = 'SELECT_COUNTRY';
